### ISSUE TITLE
Command './bin/scalabel --config app/config/default_config.yml' didn't work

### ISSUE THREAD

**Issue by AromaticJ** [ucbdrive/scalabel#1]
Hi, thanks very much for your remarkable work! But for me, something wrong with my installation to win10 os.
Under the file path of scalable, I opened powershell windows to key in command, until command './bin/scalabel --config app/config/default_config.yml', it worked well. But the os win10 seems have no idea about which exe can be used to open the scalabel file. So that ,I was not able to proceed to next step.
I guess this command is not prepared for win10 os?
How can I proceed to the next step?

**Comment by seanremy** [comment]
Hi! Thanks for trying our tool. Do you have golang installed? You just need to compile the executable first.

Our tool should have no problem working on win10, so let me know how I can help you fix this.

**Comment by AromaticJ** [comment]
I installed golang in win10 firstly, and I can make sure my installation is no problem, because when I key in 'go help' into powershell windows, help list is available. 
After I key in the command 'go build -i -o bin/scalabel ./server/go', on error occured in powershell windows, but also nothing of output show me. I have no idea what product the compile command generated, or where the product is generated. I'm familiar with go language, so that I can't understand what is the meaning of command 'go build -i -o bin/scalabel ./server/go', what the only thing I know is no error occured after I key in this command. 
Is an .exe file will be generated if the command executed rightly? And where it will be?

**Comment by AromaticJ** [comment]
Thanks for your kind reply! 
Just now, I have tried command 'go build -i -o C:\Go\bin\scalabel ./server/go', and a file named 'scalabel' but no suffix and of course not executable does generated in this path. My golang was installed under the path 'C:\Go', so that I set the $GOPATH like above. If I add an suffix like '.exe' after scalabel, (so that my command became 'go build -i -o C:\Go\bin\scalabel.exe ./server/go'), and an file scalabel.exe does generated, but seems didn't work when I double-click it.

**Comment by seanremy** [comment]
Go build should make the file executable by default. If it doesn't, then you can always [change the permission of the file yourself](https://www.quora.com/How-do-you-perform-the-equivalent-of-CHMOD-on-a-Windows-server-which-by-the-way-cant-run-a-CHMOD-command). Make sure you actually run the file from the command line, don't double click it. You can do this by just navigating to the directory in powershell and running the filename as a command.

**Comment by AromaticJ** [comment]
Yes, I navigated to the directory in powershell and run the filename with the last command './bin/scalabel --config app/config/default_config.yml' and then win10 ask me to select an program to run it.....
 It seems that this command didn't call right program automatically to execute 'scalabel'. 

I'd like to confirm does it meaning my compilation is successful if the no suffix file 'scalabel' already generated?
And I also confirmed the file 'scalabel' is completely accessible.

**Comment by bqdmm** [comment]
I have the same problem with you! @AromaticJ

**Comment by seanremy** [comment]
So on Windows, the command to run it is not "./bin/scalabel --config ...", but rather something more like "scalabel.exe --config ...", if you're already in the go/src directory. Could you try this for me? I have confirmed the tool works on Windows on my machine.

**Comment by seanremy** [comment]
Ended up being a duplicate with #3 . Windows support is coming in our next release, this week.
