### ISSUE TITLE
Labeling interface breaks if no Categories or Attributes yaml files are uploaded

### ISSUE THREAD

**Issue by ChengshuLi** [ucbdrive/scalabel#11]
Hi,

Another issue I found is that if I don't upload any Categories or Attributes yaml files, the labeling interface won't function properly. I briefly inspected the browser console and it seemed like there was a front-end null pointer error, i.e. looping through an non-existing array of attributes.

Is this behavior intended? For some tasks, I feel like I don't need any attributes. For now, I have to work around this by passing an empty yaml file as a placeholder.

Please let me know. Thanks a lot!

Here are some screenshots. 
![image](https://user-images.githubusercontent.com/6732996/42190940-e73f5a98-7e14-11e8-8f25-e2834c3f3694.png)
![image](https://user-images.githubusercontent.com/6732996/42190950-f7def9a8-7e14-11e8-8157-9dab1622be5b.png)

**Comment by ChengshuLi** [comment]
@seanremy Why is this issue closed?

**Comment by seanremy** [comment]
Meant to post earlier -- this issue has been resolved in our internal repo and will be fixed here in the next release. For now please continue to upload placeholders. Thanks!
