### ISSUE TITLE
Moving scroll bar also trigger drawing a point after mouse up

### ISSUE THREAD

**Issue by ChengshuLi** [ucbdrive/scalabel#12]
After zooming in, when I move the scroll bar at the bottom, I will also trigger drawing a point after I release my mouse (i.e. triggered by mouseup event). I believe this is probably unintended. 

Any help will be greatly appreciated. Thanks

![image](https://user-images.githubusercontent.com/6732996/42290513-8dd430e8-7f7a-11e8-9b3d-399bf911ecca.png)

**Comment by seanremy** [comment]
This will be fixed in our next release, thank you for pointing it out!!
