### ISSUE TITLE
Name of the image file on the labeling results

### ISSUE THREAD

**Issue by Pharaun85** [ucbdrive/scalabel#13]
Hello
I have noticed that the name of each of the files labeled is not provided at the labeling results JSON file as is given in the partial results file. (the one that is created each time the worker press save)
I'm trying to develop a script to create ground truth images from the results file in JSON format. The problem is that if I want to know which image corresponds to the coordinates returned by the labeler and the size of that image, it can't be done with the given JSON file. 
Is there any way to make this correspondence?

Thanks

**Comment by seanremy** [comment]
Take a look at the labelIds field of the items field of your submission .yml, it has what you're looking for!
