### ISSUE TITLE
Vertex undefined when on midpoint of another edge

### ISSUE THREAD

**Issue by daniel-pp** [ucbdrive/scalabel#15]
During 2d Segmentation Labeling, I sometimes cannot access an already labeled and saved image, getting only the "loading..." screen. In the JavaScript console, there is an accompanying error:
`TypeError: v is undefined shape.js:143:11`

Looking at the submission more carefully, this always happens when a vertex in the label has "id": -1. This in turn seems to happen when accidentally (but not rarely) a vertex of one polygon happens to lie on the midpoint of another polygon's edge (which presumably has id = -1 because it is temporary), for example:
<img width="449" alt="vertex_on_midpoint_bug" src="https://user-images.githubusercontent.com/35227976/42890208-8a0f129c-8aac-11e8-93b1-f791f4bacb00.png">
 
Can you confirm the problem?
In any case, thank you for the nice and very useful tool!

**Comment by xanderchf** [comment]
Hello,

Thanks for pointing out the problem! We are developing the tool in our internal repo and expect to solve this in the next release. For this issue, simply delete line 159 in seg2d.js and everything will work fine.
