### ISSUE TITLE
Unable to delete finished lane marking? 

### ISSUE THREAD

**Issue by kevinsu628** [ucbdrive/scalabel#157]
I have been playing around lane marking for a while, and I couldn't find any way to delete a drawn lane (after I hit enter).

Am I missing something here, or is deleting a finished lane not supported?

**Comment by csush** [comment]
It works for me. Just to reiterate - right after pressing `Enter`, if you press `Delete` it should delete the polyline since that polyline remains selected. If it is unselected then you have to double click anywhere on the polyline to select it first, and then press `Delete`.

**Comment by kevinsu628** [comment]
Thank you! I didn't realize it's double click.
