### ISSUE TITLE
Pointcloud selection problems

### ISSUE THREAD

**Issue by daniel-pp** [ucbdrive/scalabel#16]
While testing the 3D Bounding Box Labeling Tool for point clouds, I noticed the following problems:

1. It seems impossible to move or reshape an existing bounding box (one that was created, deselected and selected again).
2. After adding a new bounding box, it seems impossible to switch to another one in the 3d view. Changing the selection in the bounding box list deletes the one that was just added.

**Comment by DKandrew** [comment]
Hi daniel-pp,

Try to hit "Enter" after you select the bounding box. You should be able to move/reshape the bounding box now.
