### ISSUE TITLE
How do I debug?

### ISSUE THREAD

**Issue by readicculus** [ucbdrive/scalabel#168]
I've managed to build this on my own and get a local server running(not the docker), but I would like to start making my own changes and need a good way to debug.
Can someone help me figure out what I need in my launch.json in vscode inorder to attach the node stuff so I can debug js.
Currently trying something like this:
```
"configurations": [
       {
            "type": "node",
            "request": "attach",
            "address": "127.0.0.1",
            "name": "Attach",
            "port": 8686
        },
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/scalabel",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "args": [
                "--config",
                "${workspaceFolder}/data/config.yml"
            ]
        }
]
```
But its not working, It does run the server but then I cannot figure out how to attach a debugger.  So when I build the executable I use the --watch flag as mentioned but I can't seem to figure out a way to efficiently debug this in a nice way.  I don't really get how node compiles these days as it's been a good 5 years since I've used node and it seems to have come a long way but I imagine I somehow need to attache the src directory to gdb process.

**Comment by fyu** [comment]
Are you debugging the server or client code?
