### ISSUE TITLE
What is the item list?

### ISSUE THREAD

**Issue by uzair789** [ucbdrive/scalabel#18]
Hi,

When I start the server and go to the localhost:8686 address in the browser, I see a form where I am asked to enter the project name, item type, label type etc.

I dont understand what I should enter for item list. What exactly is this? I have a bunch of images where I would like to draw bounding boxes around objects to train a detector. If somebody can tell me what I need to enter for item list, Categories, Attributes, task size and vendor id, it will be a huge help. Thanks.

**Comment by seanremy** [comment]
We include an example item_list.yml in the examples folder. The item list in your case is a yml representation of your images.

If you have your images hosted somewhere, you will include links to these images.

If you wish to serve your own data on the same domain as this server, then the item_list.yml you provide at project creation needs to contain URLs to this server. Any files or directories you place in "app/src/" will be uploaded to the server with the prefix path removed. For example, you could place a directory "images" in "app/src/". If you are just testing the server locally, you can then specify in your item list URLs such as  "localhost:8686/images/image_1.jpg".

**Comment by uzair789** [comment]
Thanks. I can see the examples the folder. What about the task size? Is that something for multiple labellers who are labelling the data?

**Comment by seanremy** [comment]
That's exactly correct! When you upload a project, it gets split into a number of tasks. Say you want to label 100 images, and you want 5 annotators to each label 20 images, then you assign a task size of 20. We are also working on support for multiple annotators working on the same task, so you can cross-reference their work.

**Comment by csush** [comment]
I have a relevant problem. For example, when I put the task size as 1000 for a dataset of 3957 images, the project gets divided into 4 tasks of 1000, 1000, 1000, 957 images each. The first 3 tasks can be navigated around properly. But the last task of 957 items does not navigate properly. That task page opens at item 130, and the next item is 260 instead of progressing to 131 and so on (390 -> 520 -> ...). Any tips on which file I should look into to fix this?
