### ISSUE TITLE
Can not draw object of small size in 2d-segmentation

### ISSUE THREAD

**Issue by nieyan** [ucbdrive/scalabel#216]
![20190912134354](https://user-images.githubusercontent.com/11882730/64757621-38086c00-d565-11e9-9731-5abd03999169.png)

I zoom in the image to the maximum, and want to draw the lane mark of the single dash line.  But I can not finish the poly2d because the polygon will disapper when I click on start vertex. Dose labeled object have limit of size ? That seems unreasonable.

**Comment by fyu** [comment]
resolved by #220

**Comment by nieyan** [comment]
Thank you very much！
