### ISSUE TITLE
Images in readme are not available

### ISSUE THREAD

**Issue by KiriLev** [ucbdrive/scalabel#262]
Hi!
Some images in readme are not available. 
For example, on image with alt "scalabel interface" with url  https://camo.githubusercontent.com/9af5f28a0cb1af0d829fab5634ad9262ce528948/68747470733a2f2f7777772e7363616c6162656c2e61692f646f632f64656d6f2f726561646d652f7363616c6162656c5f7465617365725f696e746572666163652e6a7067

Response: "Cannot proxy the given URL"

**Comment by MaesIT** [comment]
Hi KiriLev,

Seems their website is down at the moment.
As a work around you could download the site locally.
The instruction to do this can be found on: https://github.com/ucbdrive/scalabel-doc

**Comment by fyu** [comment]
The website is back online. Sorry for the inconvenience.
