### ISSUE TITLE
Unable to return to previous image with left key

### ISSUE THREAD

**Issue by skmatz** [ucbdrive/scalabel#279]
## Overview

It is no longer possible to return to the previous image with the left key despite being possible at least until last week. (It is possible to go to the next image with the right key.)

## Environment

- Docker
- Item Type: Video
- Label Type: 2D Bounding Box

**Comment by gycn** [comment]
Hi @skmatz, we are currently refactoring a substantial portion of the codebase. If you see unexpected behavior, please check out an earlier commit of the project which you know will work. The refactoring should be completed soon at which time all of the features will work again. Once everything is complete, we will publish a release with notes as well as instructions on how to port all of your data over.

**Comment by skmatz** [comment]
OK. I reverted to the previous [5ee3481](https://github.com/ucbdrive/scalabel/commit/5ee3481a62831dc2864dbfcc04b11cce9e244ace) commit solved the problem.

**Comment by fyu** [comment]
This is resolved by #310
