### ISSUE TITLE
Unable to set item type to video

### ISSUE THREAD

**Issue by skmatz** [ucbdrive/scalabel#292]
## Overview

In my local environment, it is recognized as an image task even though item type is input as video. For example, when I input `example/image_list.yml` as item type video, it is divided into 99 tasks one by one.

## Environment

- Ubuntu 16.04
- Go v1.11.13
- Node.js v12.13.0
- Item Type: Video

**Comment by noahjimenez5844** [comment]
Would it also be possible to post your logs after you create the project?

**Comment by gycn** [comment]
Adding an update: this is unexpected behavior and we are working to resolve the problem.

**Comment by skmatz** [comment]
> Which server are you using? Nodejs or Golang?

I use Node.js v12.13.0 for server.

> Would it also be possible to post your logs after you create the project?

How to watch logs?
At least, `itemType` of `data/{project}/project.json` generated after project creation is set to `image`, and 99 (number of images) .json-files are created under `data/tasks/`.

The `project.json` is like below (There are actually 99 `items` elements).

```json
{
    "config": {
        "projectName": "example",
        "itemType": "image",
        "labelTypes": [
            "box2d"
        ],
        "taskSize": 1,
        "handlerUrl": "label",
        "pageTitle": "2D Bounding Box",
        "instructionPage": "https://www.scalabel.ai/doc/instructions/bbox.html",
        "bundleFile": "image_v2.js",
        "categories": [
            "person",
            "rider",
            "car",
            "truck",
            "bus",
            "train",
            "motorcycle",
            "bike",
            "traffic sign",
            "traffic light"
        ],
        "attributes": [
            {
                "name": "Occluded",
                "toolType": "switch",
                "tagText": "o"
            },
            {
                "name": "Truncated",
                "toolType": "switch",
                "tagText": "t"
            },
            {
                "name": "Traffic Light Color",
                "toolType": "list",
                "values": [
                    "NA",
                    "G",
                    "Y",
                    "R"
                ],
                "tagPrefix": "t",
                "tagSuffixes": [
                    "",
                    "g",
                    "y",
                    "r"
                ],
                "buttonColors": [
                    "white",
                    "green",
                    "yellow",
                    "red"
                ]
            }
        ],
        "taskId": "",
        "submitTime": -1,
        "submitted": false,
        "tracking": true,
        "policyTypes": [],
        "demoMode": false,
        "autosave": true
    },
    "items": [
        {
            "url": "https://s3-us-west-2.amazonaws.com/scalabel-public/demo/frames/intersection-0000051.jpg",
            "videoName": "b"
        },
        {
            "url": "https://s3-us-west-2.amazonaws.com/scalabel-public/demo/frames/intersection-0000052.jpg",
            "videoName": "b"
        },
	]
}

**Comment by skmatz** [comment]
Thanks, but at least in my environment the problem is not solved.
Is this a specific problem for me? Does anyone have the same problem?

**Comment by fyu** [comment]
Can you post your image list? Our manual for the input file format may not be clear enough.

**Comment by noahjimenez5844** [comment]
Also can you make sure to clear your cache (or use an incognito window), pull, and recompile the code. If this still isn't working, would it be possible to post your logs again?

**Comment by skmatz** [comment]
> Can you post your image list? Our manual for the input file format may not be clear enough.

I use [example images list](https://github.com/ucbdrive/scalabel/blob/master/examples/image_list.yml).

**Comment by skmatz** [comment]
> Also can you make sure to clear your cache (or use an incognito window), pull, and recompile the code. If this still isn't working, would it be possible to post your logs again?

Oh, It works after I cleared. It was my fault.

By the way, although it works as intended, it seems wrong that the `itemType` in `project.json` is `image`. This should be entered as video. The item type displayed in the dashboard sidebar is the same.

**Comment by gycn** [comment]
Currently, we store videos with an item type of image, but we keep a flag for it in the save files. Unfortunately, this means that the dashboard will display it as image even though it is a video.
