### ISSUE TITLE
Existing projects are empty 

### ISSUE THREAD

**Issue by mkilicar** [ucbdrive/scalabel#306]
I tried both the docker and native versions. Unfortunately, on both of them I'm getting a blank page after clicking the "GO TO ..." buttons.
I don't know whether this is related with the below error message or not: 
{"level":"error","message":"Cannot read property 'readdir' of undefined"}

Does anyone have any idea to resolve this issue?
![screenshot](https://user-images.githubusercontent.com/9872319/68587184-8075d480-0497-11ea-8975-22d84922f77a.png)

**Comment by noahjimenez5844** [comment]
@mkilicar can you try clearing/disabling your cache (on chrome go to developer tools -> network -> disable cache),  rebuilding the javascript, then re-creating your project? If that doesn't work, can you re-post your logs?

**Comment by gycn** [comment]
Did you pull from the code base recently, with a project created before updating?

**Comment by mkilicar** [comment]
@noahjimenez5844 I rebuild and recreate the project. I'm still getting the same error. I tried on both Ubuntu and Mac OS, and getting the same thing.
@gycn : 
git clone git@github.com:ucbdrive/scalabel.git
cd scalabel
npm install
node_modules/.bin/npx webpack --config webpack.config.js --mode=production
mkdir data
cp app/config/default_config.yml data/config.yml
node app/dist/js/main.js --config ./data/config.yml

**Comment by gycn** [comment]
Could you please post your npm and NodeJS versions? For reference, we usually use npm>=6.12 and node>=12.13

**Comment by fyu** [comment]
@mkilicar We could not reproduce your problem in the current docker. What's your image list? What does your project creation look like after you put in all the information?

**Comment by fyu** [comment]
@mkilicar We have updated docker #311 with latest node and npm. It may help resolve your problem.

**Comment by mkilicar** [comment]
The updated docker image is working. Thank you very much.
