### ISSUE TITLE
cannot find package "github.com/aws/aws-sdk-go/aws"

### ISSUE THREAD

**Issue by SandeepRamesh** [ucbdrive/scalabel#32]
Hi,
There are few lines of code that are missing in the Dockerfile. During build, i get the following errors:

server/go/storage.go:6:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
        /go/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
server/go/storage.go:7:2: cannot find package "github.com/aws/aws-sdk-go/aws/session" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/aws/session (from $GOROOT)
        /go/src/github.com/aws/aws-sdk-go/aws/session (from $GOPATH)
server/go/storage.go:8:2: cannot find package "github.com/aws/aws-sdk-go/service/dynamodb" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/service/dynamodb (from $GOROOT)
        /go/src/github.com/aws/aws-sdk-go/service/dynamodb (from $GOPATH)
server/go/storage.go:9:2: cannot find package "github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute (from $GOROOT)
        /go/src/github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute (from $GOPATH)
server/go/storage.go:10:2: cannot find package "github.com/aws/aws-sdk-go/service/dynamodb/expression" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/service/dynamodb/expression (from $GOROOT)
        /go/src/github.com/aws/aws-sdk-go/service/dynamodb/expression (from $GOPATH)
server/go/sat.go:7:2: cannot find package "github.com/mitchellh/mapstructure" in any of:
        /usr/local/go/src/github.com/mitchellh/mapstructure (from $GOROOT)
        /go/src/github.com/mitchellh/mapstructure (from $GOPATH)
server/go/utils.go:7:2: cannot find package "github.com/satori/go.uuid" in any of:
        /usr/local/go/src/github.com/satori/go.uuid (from $GOROOT)
        /go/src/github.com/satori/go.uuid (from $GOPATH)

Suggestion to resolve this issue:

Updated Dockerfile:
-----------------------
FROM golang
EXPOSE 8686
ADD . .
RUN go get gopkg.in/yaml.v2
RUN go get -u github.com/aws/aws-sdk-go/aws
RUN go get -u github.com/aws/aws-sdk-go/aws/session
RUN go get -u github.com/aws/aws-sdk-go/service/dynamodb
RUN go get -u github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute
RUN go get -u github.com/aws/aws-sdk-go/service/dynamodb/expression
RUN go get -u github.com/mitchellh/mapstructure
RUN go get -u github.com/satori/go.uuid
RUN go build -i -o bin/sat ./server/go
CMD ./bin/sat --config ./app/config/default_config.yml

Now the image is successfully built after update. please update if you think its right. 

Thanks,
Sandeep

**Comment by fyu** [comment]
The docker is fixed by 2c78f7dc00bd
