### ISSUE TITLE
Can't add any labels. It used to work just fine previously. 

### ISSUE THREAD

**Issue by mshong0320** [ucbdrive/scalabel#321]
Has there been any updates on the label.js? It used to be able to label points just fine but after cloning the repo today i can't add any labels when i click on the screen. 

It looks like the following picture:
![image](https://user-images.githubusercontent.com/15217071/69202409-2fa15400-0b07-11ea-812c-8c0340f86f06.png)

Using Ubuntu 16.04
Any help would be appreciated!

**Comment by fyu** [comment]
Did you see any error message in the web browser console? Can you share your project config file to reproduce the problem?

**Comment by mshong0320** [comment]
No error message in the web browser. 

Which file are you referring to?

**Comment by fyu** [comment]
The configuration files for project creation

**Comment by mshong0320** [comment]
My image_list.yml looks like as follows:
- url: http://localhost:8686/images/1570124316633739545.png
  videoName: ''
- url: http://localhost:8686/images/1570124317739251305.png
  videoName: ''
- url: http://localhost:8686/images/1570124318920366719.png
  videoName: ''
and so on

And then i used the lane_categories.yml and lane_attributes.yml files included in the ./examples/ directory.

**Comment by mshong0320** [comment]
Here is the project config file:
```
---
port: 8686
data: "./data"
src: "."
database: "local"
userManagement: false
sync: false
autosave: false
...
```

**Comment by mshong0320** [comment]
I'm going to close this as it was an issue with my npm
