### ISSUE TITLE
Project Dashboard gives a blank page

### ISSUE THREAD

**Issue by SandeepRamesh** [ucbdrive/scalabel#33]
hi,
After running scalable using docker container and when i click on 'Goto Dashboard' after entering the details on the Create Annotation Project screen, it just displays a blank screen. Could you please help me on what went wrong ?

![project_dashboard](https://user-images.githubusercontent.com/29154684/45445640-5dcc0e00-b690-11e8-8ebb-a38afb6fd32e.JPG)

**Comment by fyu** [comment]
This should be resolved in the current master. Please check it out.

**Comment by SandeepRamesh** [comment]
okay. Thank you . 👍

**Comment by SandeepRamesh** [comment]
Made it work with the updated dockerfile. 

FROM golang
EXPOSE 8686
ADD . .
RUN go get gopkg.in/yaml.v2
RUN go get -u github.com/aws/aws-sdk-go/aws
RUN go get -u github.com/aws/aws-sdk-go/service/dynamodb
RUN go get -u github.com/mitchellh/mapstructure
RUN go get -u github.com/satori/go.uuid
RUN go build -i -o bin/sat ./server/go
CMD ./bin/sat --config ./app/config/default_config.yml


**Tool is wonderful**

**Comment by fyu** [comment]
The docker file is updated in 2c78f7dc00bd
