### ISSUE TITLE
Issue cloning

### ISSUE THREAD

**Issue by Gitanjali450** [ucbdrive/scalabel#333]
While cloning with the following command:

git clone git@github.com:ucbdrive/scalabel.git

I get the following error:

Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Please let me know how to get around this problem.
Thank you.

**Comment by fyu** [comment]
There may be a problem with your git key setup. You can try to clone from https protocol with `git clone https://github.com/ucbdrive/scalabel.git`.

**Comment by Gitanjali450** [comment]
Thank you. It works.
