### ISSUE TITLE
server does not launch

### ISSUE THREAD

**Issue by Gitanjali450** [ucbdrive/scalabel#334]
Hello,

I followed the instructions given in the following document: https://www.scalabel.ai/doc/get-started.html

But when I launch the http://localhost:8686 in my web browser, it ends up with an error of 404 page not found.

Are there any additional steps to what is written in the document mentioned to be able to launch the server? Please let me know how I can solve this issue.

Thank you.

**Comment by fyu** [comment]
What's the command line output after you entered `./bin/scalabel --config ./data/config.yml`?

**Comment by Gitanjali450** [comment]
Hello,
Thank you for the response.
I get the following output after I run the command: ./bin/scalabel --config ./data/config.yml

INFO: 2019/12/04 11:08:30 Configuration:
---
port: 8686
data: "./data"
src: "."
database: "local"
userManagement: false
sync: false
autosave: false
...
INFO: 2019/12/04 11:08:30 &{8686 ./data .  local false false           0}
INFO: 2019/12/04 11:08:30 Listening to Port 8686
INFO: 2019/12/04 11:08:30 Local URL: localhost:8686
INFO: 2019/12/04 11:09:06 127.0.0.1:50576 is requesting /

**Comment by Gitanjali450** [comment]
Solved!!
