### ISSUE TITLE
Page not found: https://github.com/ucbdrive/sat

### ISSUE THREAD

**Issue by Gitanjali450** [ucbdrive/scalabel#336]
Hello,

Tha page at the following link: https://github.com/ucbdrive/sat does not exist. Could you please fix the broken link?

I was following the instructions in this file: https://github.com/ucbdrive/scalabel/blob/master/server/model/setup_backend.sh and at line 27 we need to clone this repository. Or if there is a way around this, please let me know.

Thank you.

**Comment by fyu** [comment]
The `server` folder is deprecated. The functionalities have been moved to the nodejs server.
