### ISSUE TITLE
Problem of Adding 3D Tracking Bounding Boxes

### ISSUE THREAD

**Issue by qiank10** [ucbdrive/scalabel#337]
Hello,

I download the Scalabel v0.2.0 and setup the server. Then I create a 3D bounding box tracking project. The project consists of multiple tasks and each task contains multiple point cloud frames. However, the server only works for the task 0. For the other tasks, the console outputs an error ''sat_point_cloud.js:825 Uncaught TypeError: Cannot read property 'createBox' of null'' when I try to add a new box. The demo also has this problem. Could you please help fix this problem? Thank you.

**Comment by gycn** [comment]
Hi @qiank10, could you try using the code at head of master instead? We are in the process of a large refactor. I believe this should be fixed now. Currently, you must specify videoname for tracking in order to split the project up into separate tasks, like what is done for videos.

**Comment by qiank10** [comment]
Hi @gycn, I tried the code of the master branch. However, the console says that ''split_plane.css'' is missing. The data cannot be loaded and the web page is blank. I also tried the image at the docker hub. However, there is no ''adding box'' button for 3D point cloud projects.

**Comment by gycn** [comment]
If the docker image is working for you, then sticking with that would be best. There is no button right now for adding box. You need to press the space bar to add a new box. Sorry, we are a little behind on documentation right now.

**Comment by qiank10** [comment]
Thank you for the guide. The docker image works now and the UI is more friendly than the previous version. 

As for the version 0.2.0, there is a bug in "app/src/js/v1/point_cloud/point_cloud_traking.js".
`29: for (let i = this.currentItem.index; i < this.items.length; i++) {`
The initial value should be `this.currentItem.index - this.items[0].index`. 
The same value needs to be corrected in the 40th line,
`40: if (i != this.currentItem.index - this.items[0].index) {`
Then 3D bounding boxes can be created for tasks other than the first one.

**Comment by qiank10** [comment]
When adding bounding boxes to a sequence of point cloud frames, the unit bounding boxes are generated. However, adjusting the box in the first frame doesn't change the rest. As there is no perspective problem for 3D point cloud, the boxes of one object are likely to be consistent. Is there any short key to scale the boxes in the rest frames? Thank you.

**Comment by gycn** [comment]
That is a feature that is in our roadmap but which is not available
currently. For now, you will have to adjust the boxes manually. You can
postprocess the boxes after exporting to adjust the boxes in each track to
be of the same size by taking the maximum size.
