### ISSUE TITLE
Unable to end object tracking 

### ISSUE THREAD

**Issue by hm535** [ucbdrive/scalabel#346]
I'm trying to do bounding box interpolation. In the documentation, there is a button to "END OBJECT TRACK" (alternatively Ctrl-E) - but this function is not available in the newest docker build.  In the screenshot below, you can see the DELETE button, but nothing below that.  
![image](https://user-images.githubusercontent.com/31516987/70367221-dbaaa500-1852-11ea-957f-364f24b0b787.png)
Can someone point me in the right direction please?

**Comment by gycn** [comment]
You can end a track by holding down either command or control before pressing delete

**Comment by hm535** [comment]
Thank you for the quick reply! Doesn't work unfortunately :(

**Comment by gycn** [comment]
Just to confirm. Did you select the label and then hold control before pressing delete? Would it be possible for you to open the developers console on chrome and perform this action, and send the output to us so that we may debug this?

**Comment by hm535** [comment]
Hello! Yes, the label is selected when I press delete. No action appears on the debug console when I press delete though. The last entry in the console indicates when I moved the bounding box. However, when I press ctrl+del, no additional entries appear. 
 
![image](https://user-images.githubusercontent.com/31516987/70380356-c97e4480-18ee-11ea-8ea4-8680046d2f13.png)

**Comment by hm535** [comment]
Just to make sure, I am creating the project with the following settings. Am I using the right settings for video 2D bounding box tracking? 

![project_creation](https://user-images.githubusercontent.com/31516987/70380503-37c40680-18f1-11ea-915d-a780f3a7f9ee.png)

I'm inclined to think the build is lacking this functionality for some reason :( I follow the readme to pull the latest docker image and run it. Do you have older versions of the docker image that I could pull and run?

**Comment by gycn** [comment]
Yes this is correct. You can use the 0.2.0 release and build the project
from source.

I am trying to reproduce this issue, but the function works on my local
computer. I will try again later today to see if I can reproduce it

**Comment by gycn** [comment]
In the meantime could you try building the docker image locally?

**Comment by gycn** [comment]
@hm535 I think that we may have had a miscommunication. When I said Ctrl + Delete earlier, I meant pressing the Delete or Backspace key on the keyboard. Could you try it this way and check whether  it works?

**Comment by hm535** [comment]
@gycn, I did try Ctrl + Del on the keyboard - but it didn't work. I did not know about the Ctrl + Backspace option, and I just tried it - and that solved the problem! I'll close this issue as solved for now. Thank you for the help! :+1:
