### ISSUE TITLE
error message cannot read property readdir of undefined

### ISSUE THREAD

**Issue by psyg0501** [ucbdrive/scalabel#347]
When I fill in all the fields in new project and click submit and then dashboard, nothing happens. In the terminal its says something like this:
level":"error message cannot read property readdir of undefined

How to resolve this?
![screen1](https://user-images.githubusercontent.com/12151488/70394108-ff582180-19f1-11ea-8241-0b70870c31f3.JPG)

**Comment by gycn** [comment]
Are you building the project locally or using the docker image? If you are building locally, this is likely due to version issues with node and npm. I would suggest using docker as an easy solution

**Comment by psyg0501** [comment]
I compiled it in Ubuntu 18.04 LTS in a Virtualbox on my windows desktop. Earlier I also tried it on a cloud-based instance of the same OS (a 16 GB 2-vcpu instance). Docker was my first attempt since I believed docker images contain all the dependencies and are guaranteed to run. But unfortunately it did not run on my instance. The last command given in documentation did not run. I believe this command mounts a volume and runs the container for data persistence and for that reason it is a long compound command. I am not sure if I ran it correctly by just copying and pasting it.

I tried the `compiled version` instructions - both those given in the documentation (https://www.scalabel.ai/doc/get-started.html) and those on the Github page (https://github.com/ucbdrive/scalabel). Unfortunately I had no luck and I don't even know which one is the right/ latest set of instructions. In one set of instructions Go is mentioned, in the other one it is absent. Also, I did not understand whether I need to have a Github account, and Amazon AWS account or whether these are optional. I did not understand why one needs User management via AWS cognito as no background information was given about this. I do have an AWS account so I proceeded to created my AWS cognito ID and filled all those fields/ strings but no luck. I was not sure what was to be filled in Callback URL(s) and Sign out URL(s), though. 

In one instance, the last response upon launching the server was "Listening to port 8686 ..."  and in another instance (in the case of following the instructions posted on Github) there was just the frozen cursor. I don't know which one is the right outcome. 

Thanks.

**Comment by janklatte** [comment]
Got the same problem with a native installed ubuntu 18 installation. (not using the docker installation)

**Comment by gycn** [comment]
@psyg0501 @janklatte I believe both of these issues are due to out of data npm or node installations. Could you please make sure your NodeJS version is >= 12.11.0 and to run `npm install -g npm@latest`? Otherwise, please use the docker container instead.

@psyg0501 The instructions on the website are outdated, but the ones on the README are up to date. What error do you get when trying to run the docker? Did you make sure to either pull or build the docker beforehand?

**Comment by janklatte** [comment]
Hi thanks for the quick reply! I described the issue when working with docker here:
https://github.com/ucbdrive/scalabel/issues/350

**Comment by janklatte** [comment]
Updating the NodeJs version fixed the issue. Thank you!
