### ISSUE TITLE
Unable to delete the vertex with "ESC" or "DELETE" in seg2d

### ISSUE THREAD

**Issue by kduy** [ucbdrive/scalabel#36]
Hi guys,
When annotating the image with seg2d, i am unable to delete the previous vertex with "DELETE" like in this video :
http://data-bdd.berkeley.edu/label/seg/video/delete.mov
is this feature no longer available ?
Thanks

**Comment by xanderchf** [comment]
Thanks for bringing this up! Deleting vertices is not currently supported yet, but this feature will become available in the next release. Stay tuned:)

**Comment by fyu** [comment]
This is resolved in the current master.
