### ISSUE TITLE
Fusion is not working

### ISSUE THREAD

**Issue by smajida** [ucbdrive/scalabel#367]
**Describe the bug**

**To Reproduce**
1. Go to 'the main page of project creation'
2. Click on 'Item Type'
3. Scroll down to 'Fusion'
4. See error:
there is no error shown, but the fusion tool does not work. 

**Expected behavior**
If I understood it correctly, the fusion tool is to fuse LiDar with image and by annotating an object in LiDar, the corresponding object is annotated in the image and the annotator is looking at both data modalities at the same time.

**Screenshots**
 - OS: Ubuntu16.04
 - Browser Firefox

**Comment by fyu** [comment]
Thanks for your interest in scalabel. The fusion feature is still experimental now. We will make changes to avoid confusion. Please raise the future issues at https://github.com/scalabel/scalabel
