### ISSUE TITLE
1

### ISSUE THREAD

**Issue by smajida** [ucbdrive/scalabel#368]

**Comment by fyu** [comment]
The websites of those failed images may have disabled cross-origin resource sharing (CORS)

**Comment by smajida** [comment]
@fyu no I checked the websites. Those websites have the following configuration enabled fro CORS in Apache2 server.

<Directory /var/www/html>
     Order Allow,Deny
     Allow from all
     AllowOverride all
     Header set Access-Control-Allow-Origin "*"
</Directory>
`

**Comment by smajida** [comment]
Could you please try those failed images in your side as well to see the error message?
