### ISSUE TITLE
Cannot load initial page

### ISSUE THREAD

**Issue by Pharaun85** [ucbdrive/scalabel#37]
I updated scalabel because i had problems with the old version. For some of the pictures the program did not save the results, raising an empty value exception in the browser's console. 
Now I cannot  even access to the main page, as the images shows. 
![imagen](https://user-images.githubusercontent.com/40762766/45829289-e84ce700-bcfa-11e8-8239-c70d2bb0e7d9.png)
![imagen](https://user-images.githubusercontent.com/40762766/45829325-f995f380-bcfa-11e8-86c1-e34fe8a6c3da.png)
I updated node version as I read in other issues, but still does not work.

Can someone please tell me what I'm doing wrong?

Thanks

**Comment by antoinebrl** [comment]
Did you solve the issue? I have the same problem.
