### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by ashutoshsoni891** [ucbdrive/scalabel#372]
Hi !

I can see there is no Keypoint annotation detection. I would like to add that functionality, also there is no option  to do multiple annotations like segmentations, lines in a single image.

**Comment by gycn** [comment]
Hi @ashutoshsoni891, thank you for reaching out. We would love for you to contribute to the project! First off, we have actually migrated the repo to here: https://github.com/scalabel/scalabel. The latest code can be found there. 

Currently, Scalabel does support keypoint annotation, but not multi-type labeling. Keypoint annotation requires the user to define and pass in a label specification when creating a project. You can look in the `examples/human_pose_template.yml` for an example. 

Multi-type labeling is definitely a feature we would like to support, but which we have not yet gotten around to. If you would like to help us work on this feature, I think the best way to get started is to create a separate issue on the new repo for this specific topic. We can discuss what an initial implementation might look like there and get you set up with the codebase.
