### ISSUE TITLE
Task size is required

### ISSUE THREAD

**Issue by azahreba** [ucbdrive/scalabel#4]
![image](https://user-images.githubusercontent.com/5867788/41874882-77f0cdc0-78c9-11e8-905f-87646bc86dad.png)

This code doesn't work for some reason

```
if (itemSelect.value === 'video') {
    frameRate.required = true;
    frameRate.parentNode.style.display = '';
    taskSize.required = false;
    taskSize.parentNode.style.display = 'none';
```

**Comment by seanremy** [comment]
I'm having a hard time replicating this error. Is there anything specific you did when interacting with the "Item Type" box?

**Comment by azahreba** [comment]
Hmm..
no, just selected everything step by step as it is on the screenshot.
For me it popups this message every time I select "Video".
What's interesting "required" attribute is False for that input..

![image](https://user-images.githubusercontent.com/5867788/41876352-ccf71fa0-78cd-11e8-8fc7-f897e436d3d7.png)

**Comment by azahreba** [comment]
No, everything is correct! I tried everything one more time.
When I display that input and fill in a value I'm able to create a project.
But after that I have another issue with frames loading
![image](https://user-images.githubusercontent.com/5867788/41877322-211c7e88-78d1-11e8-9cdb-158e6f0b770e.png)
Do you know what might be a reason for that?
I run a server using docker on windows 🤦‍♂️

**Comment by seanremy** [comment]
Ah, this one I know! The item_list.yml is supposed to contain URLs. As this is a tool that allows remote workers to annotate your data, the items need to be accessible to others. Javascript can't access your disk (by design) and therefore is spitting out errors when you try to do so.

We're considering adding the ability to serve an items directory. Would that be helpful to you?

**Comment by azahreba** [comment]
Yeah, exactly.
It would be perfect!
Thanks ;)

**Comment by seanremy** [comment]
Ok so for now we don't have a configurable items directory, but if you put your data directory inside scalabel/app/src then your data is accessible, as a temporary fix. Don't do this long term as it also allows users to view Tasks/Assignments/Submissions, which are not supposed to be accessible.

I'll work on adding that items folder.
