### ISSUE TITLE
Image localhost:8686/images/xxx.jpg was not found.

### ISSUE THREAD

**Issue by jiaobingle** [ucbdrive/scalabel#58]
i put my pic in /app/dist/images,
and run scripts/prepare_data.py to make the  'image_list.yml'
but when i create my annotation project and 'go to dashboard', i always show image was not  found, i don't know why, thx!

**Comment by jiaobingle** [comment]
@dschoerk 
i'm so sorry ,but i can not make it correctly, how did you get the compiled code, with docker or compiling the code by yourself, thx, i got it by building the docker image myself, may be it support run purely.

**Comment by jiaobingle** [comment]
OK, i have solved it by compiling the code with method 2, thx!

**Comment by dschoerk** [comment]
i did run the pre-built docker image as well as a self compiled version (0.2.0-rc4). both worked fine.

**Comment by sangeeth93** [comment]
Hi, I've tried using the prebuilt docker image and also building from source code and in both the cases I'm facing this "Image not found issue", and upon terminal I have this running for all the list of images in image list
![Screenshot from 2019-05-02 21-42-25](https://user-images.githubusercontent.com/35250966/57070461-2086c000-6cf5-11e9-85cc-802d7ddbe288.png)
people who have resolved can post how they have resolved.
@jiaobingle what is method 2?
