### ISSUE TITLE
Semi-automatic Annotation

### ISSUE THREAD

**Issue by jiaobingle** [ucbdrive/scalabel#59]
as we can see in the  document 'You can directly upload the exported results from a previous annotation project and the labels will show up again in the new tasks'.
but could anyone display it in details, thx!

**Comment by fyu** [comment]
We updated the instruction for project creation to provide more details: https://www.scalabel.ai/doc/create-project.html. The example list for auto matic annotation creation is https://github.com/ucbdrive/scalabel/blob/master/examples/image_list_with_auto_labels.json.

**Comment by jiaobingle** [comment]
thx, i have found "You can also upload the prediction Json file of detection and segmentation models in the BDD data format to achieve semi-automatic annotation"  as instruction.

**Comment by myhooo** [comment]
Hello, I have tried detection semi-automatic annotation following your instruction. I wonder to know whether scalabel can make the tracking semi-automatic annotation?thx!!!
