### ISSUE TITLE
Use local images path

### ISSUE THREAD

**Issue by AromaticJ** [ucbdrive/scalabel#8]
Hi, I run 'scalabel' on ubuntu with example 'image_list.yml' successfully.
How can I access local image path by modify 'image_list.yml' file?

- {url: '/media/aj/KU/HRYT/image/TV_CAM_20180614_125034/image_100.jpg'}

Just replace original path by myself's local path seems didn't work.
I know url: indicates an web path...

**Comment by Pharaun85** [comment]
Hi
I had the same problem. You should store the images in a folder inside "app/src/foldername". Then the path inside the yml file should be like "./foldername/filename". (you can use the script provided)
If your images must be stored in a different path then you can create a simbolic link between the path where the images are placed and the "app/src/" path, it worked for me.

**Comment by AromaticJ** [comment]
Hi ,I tried your method, but didn't work for me.
I stored my images in path '/home/aj/scalabel/app/src/foldername' and changed yml file like:

- {url: './foldername/image_0001.jpg'}

And images are 'loading' forever.....can't show

**Comment by Pharaun85** [comment]
Hi
Can you try without the apostrophe?
Maybe I confused you by using it in my answer. 
I have it like this one: - {url: ./Imgdata/um_000362.jpg}

**Comment by seanremy** [comment]
Strings in yaml can be quoted, so that shouldn't be the issue. Double check the path and config, and if all else fails please 1) show me the created project.json (in your data directory) and 2) check the javascript console in your browser (cmd+alt+j in chrome on mac, for example) and show me any error it shows.

**Comment by uzair789** [comment]
Hi, I also have the same problem. I created a folder named images in app/src and added a path to that image in a yml file. Below is the first line of my yml file
    - {url: ./images/pegs.png }

It just shows loading on the screen. I am working on ubuntu 14.04 with a chrome browser.

**Comment by mlandry22** [comment]
After trying a few variations suggested above, the app was able to locate the images when I placed it in `app/dist` based on the *Serving Data* section of this part of the documentation: https://www.scalabel.ai/doc/data-preparation.html

**Comment by yxchng** [comment]
I tried all the methods mentioned above and it does not work

**Comment by tesfagabir** [comment]
I also have the  same problem. The local images can not be loaded for annotation. Could you please help!!!

**Comment by csush** [comment]
> After trying a few variations suggested above, the app was able to locate the images when I placed it in `app/dist` based on the _Serving Data_ section of this part of the documentation: https://www.scalabel.ai/doc/data-preparation.html

This worked for me as well, after running the `node_modules/.bin/npx/webpack ... ` command mentioned in docs and restarting the server.

**Comment by trungnguyenduy** [comment]
I use docker image and want to set image_list as local path, how can I do it?

**Comment by csush** [comment]
> I use docker image and want to set image_list as local path, how can I do it?

You'll need to get inside the running container and put your images inside app/dist as a persistent volume.

**Comment by trungnguyenduy** [comment]
@csush You mean i need to create new directory  app/dist/images when run docker container then mount a volume persistent to host path (/images) or just mount to app/dist? Also why scalabel didn't make easy way to add local image list and they have plan to do this in next version. I checked https://www.scalabel.ai/doc/data-preparation.html but cannot access, it is down now
