### ISSUE TITLE
Cannot run the 3D bounding box annotation with example list

### ISSUE THREAD

**Issue by PattyLiang** [ucbdrive/scalabel#88]
Hello, 

I try to use the point cloud list in the example folder to annotate the 3D bounding box.
But it always show the message as below:

ERROR: 2019/03/28 13:06:04 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401598139528987.ply: dial tcp: i/o timeout
ERROR: 2019/03/28 13:06:13 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401598139528987.ply: dial tcp: i/o timeout
ERROR: 2019/03/28 13:06:14 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401599138308593.ply: dial tcp: lookup s3-us-west-2.amazonaws.com on 8.8.4.4:53: read udp 172.17.0.2:58204->8.8.4.4:53: i/o timeout
ERROR: 2019/03/28 13:06:14 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401599138308593.ply: dial tcp: lookup s3-us-west-2.amazonaws.com on 8.8.4.4:53: read udp 172.17.0.2:58204->8.8.4.4:53: i/o timeout
ERROR: 2019/03/28 13:06:44 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401600135798773.ply: dial tcp: i/o timeout
ERROR: 2019/03/28 13:06:44 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401600135798773.ply: dial tcp: i/o timeout
ERROR: 2019/03/28 13:06:54 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401601134108834.ply: dial tcp: lookup s3-us-west-2.amazonaws.com on 8.8.4.4:53: read udp 172.17.0.2:39671->8.8.4.4:53: i/o timeout
ERROR: 2019/03/28 13:06:54 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401601134108834.ply: dial tcp: lookup s3-us-west-2.amazonaws.com on 8.8.4.4:53: read udp 172.17.0.2:39671->8.8.4.4:53: i/o timeout
ERROR: 2019/03/28 13:07:24 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401602133158775.ply: dial tcp: i/o timeout
ERROR: 2019/03/28 13:07:24 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401602133158775.ply: dial tcp: i/o timeout
ERROR: 2019/03/28 13:07:34 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401603132027217.ply: dial tcp: lookup s3-us-west-2.amazonaws.com on 8.8.4.4:53: read udp 172.17.0.2:57187->8.8.4.4:53: i/o timeout
ERROR: 2019/03/28 13:07:34 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401603132027217.ply: dial tcp: lookup s3-us-west-2.amazonaws.com on 8.8.4.4:53: read udp 172.17.0.2:57187->8.8.4.4:53: i/o timeout
ERROR: 2019/03/28 13:08:04 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401604130374562.ply: dial tcp: i/o timeout
ERROR: 2019/03/28 13:08:04 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401604130374562.ply: dial tcp: i/o timeout
ERROR: 2019/03/28 13:08:14 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401605128620717.ply: dial tcp: lookup s3-us-west-2.amazonaws.com on 8.8.4.4:53: read udp 172.17.0.2:51217->8.8.4.4:53: i/o timeout
ERROR: 2019/03/28 13:08:14 /opt/scalabel/server/http/sat.go:395: Get https://s3-us-west-2.amazonaws.com/scalabel-public/demo/luminar/1525401605128620717.ply: dial tcp: lookup s3-us-west-2.amazonaws.com on 8.8.4.4:53: read udp 172.17.0.2:51217->8.8.4.4:53: i/o timeout

Could anybody help with this issue? Thanks a lot.

**Comment by gycn** [comment]
Hi Patty,
I'm sorry you're having issues with the tool. Could you try to go to a few of the links that are shown in the error messages and see if you can successfully download the files?

**Comment by PattyLiang** [comment]
Hi Gycn,

I can download the file directly via the link. Also can open images in the image_list.yml and draw 2D bounding boxes as ground truth. I think the server on the port is OK due to there is no difference between point_cloud_list.yml and image_list.yml. Maybe something wrong in the code, but I cannot figure out. Thanks.

**Comment by gycn** [comment]
Hi Patty,
I am having trouble reproducing your issue. Could you please list your Golang version, npm version, operating system, server port, and Scalabel repo commit number? 

In the meantime, I believe that these errors should not inhibit you from using the point cloud labeling tool. When you click the "Enter" button on the project creation page, there will be a delay as the server will attempt to download the files for pre-processing from the links. In the event that these files cannot be accessed, the server will print errors, as seen from the output you provided. However, in the event that the server cannot access these files, it will still continue with creating the project and allow you to label the data, but you must wait for it to finish processing all the files. 

If you wish to remove these errors and not wait for the server to try to process the files, you can comment out lines 385-398 in sat.go.

**Comment by PattyLiang** [comment]
Hi Gycn,

You are right. If I ignore the message and wait for server to finish processing the data, I can use the tool. But I cannot use in my created amazon list even it also can download directly by the link. The tool show the message that "Point cloud at https://s3-us-east-2.amazonaws.com/itri-charlie/1525401598139528987.ply was not found". Do you have any suggestion for fix it? Thanks.

**Comment by gycn** [comment]
Hi Patty,

Please follow the instructions here:
https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html to enable CORS on
your bucket and see if that fixes the problem.

**Comment by PattyLiang** [comment]
Hi Gycn, 

It works, thanks for your comment. I've enable and set the CORS permission to allow all origins access the data can fix it.
