### ISSUE TITLE
How to output the catgory of each 3D bounding box

### ISSUE THREAD

**Issue by PattyLiang** [ucbdrive/scalabel#89]
Hi all,
Here is one of the testing result.
  {
    "name": "https://s3-us-east-2.amazonaws.com/itri-charlie/1525401598139528987.ply",
    "url": "https://s3-us-east-2.amazonaws.com/itri-charlie/1525401598139528987.ply",
    "videoName": "",
    "attributes": null,
    "timestamp": 0,
    "index": 0,
    "labels": [
      {
        "id": 0,
        "category": "",
        "attributes": {
          "Occluded": true
        },
        "manualShape": true,
        "box2d": null,
        "poly2d": null,
        "box3d": {
          "dimension": [
            1,
            1,
            2.1364702656539034
          ],
          "location": [
            0,
            0,
            0
          ],
          "orientation": [
            1.4686250195162456,
            0.28804298347878876,
            -2.5480047758817284
          ]
        }
      }
    ]
  },

I found there is no class type inside the category item for 3D bounding box labeling, although there has the selected class type inside the category item for 2D bounding box. How can I do for fix it? Thanks.

**Comment by gycn** [comment]
Hi Patty,
This is a feature that will be added in the next release. I am currently working on a fork for a temporary fix for you to use.

**Comment by gycn** [comment]
Hi Patty,
I've introduced a fix for this in #90. Please use this branch for now.
