### ISSUE TITLE
Empty fields in project dashboard

### ISSUE THREAD

**Issue by Pharaun85** [ucbdrive/scalabel#9]
Hi
I'm using scalabel to build a small dataset. I divided the project in several tasks and just finished labeling the first one. However the fields _Labeled Items, Submissions and Task result_ still empty. Is this an issue or i made a mistake finishing the task? (I just press the save button when i finished labeling)
![imagen](https://user-images.githubusercontent.com/40762766/42167155-6be05f52-7e0d-11e8-97f6-786c8b692ce4.png)

Thanks for your help

**Comment by seanremy** [comment]
These fields will be in an upcoming release. Apologies for any inconvenience!
